title: Temerio
iconURL: assets/default-icon.png
theme: 

# for a clean URL
permalink: :slug

social:
  twitter: Agustinorella11
  github: Temerio

plugins:
 - jekyll-feed
 - jekyll-seo-tag

### comments & analytics
hyvor_talk_website_id: 14
google_analytics: UA-NNNNNNNN-N
